name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Space Shooter GIF
        uses: czl9707/gh-space-shooter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          strategy: random
          # ISSO AQUI impede que ele jogue o arquivo na branch main:
          commit-message: "skip" 

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
          # Garante que ele pegue apenas o arquivo .gif gerado
          fqdn: "" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}